theme: jekyll-theme-minimal
title: Welcome to Dr. Sandro Tsang's homepage
description: Snippet examples stored in github
lsi: false
safe: true
source: _sources
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  - jekyll_video_tag
social_links:
  twitter: jekyllrb
  github:  jekyll
  linkedin: jekyll
 social:
  type:  # Person or Organization (defaults to Person)
  name:  # If the user or organization name differs from the site's name
  links:
   - "https://twitter.com/skf_tsang"
   - "https://www.linkedin.com/in/sandro-tsang"

