theme: jekyll-theme-minimal
title: Welcome to Dr. Sandro Tsang's homepage
description: Snippet examples stored in github
lsi: false
safe: true
source: _sources
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
plugins:
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
gems:
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-sitemap
  - jekyll_video_tag
